### PR TITLE
CI: test builds using other configuration flags

### PR DESCRIPTION
**Pull request by anselmolsm**
Build other combination of configuration flags besides the default one.

Please note that I see this as a temporary way of testing builds. There is a matrix feature provided by the CI that could be better explored.

### CODE REVIEW

**Comment by anselmolsm** [comment]
#115 says CI should test --enable-avahi as well (I missed the point in the git history when avahi became optional).

**Comment by hamishwillee** [comment]
@lbegani , @SaliniVenate So who is going to do this?

**Comment by anselmolsm** [comment]
@lbegani combinations that actually enable/disable different code paths should be tested.

I bet many of the cases listed above are repeating tests, considering the CI is testing only if the code builds successfully.

**Comment by lbegani** [comment]
@anselmolsm @hamishwillee Can you kindly review to see if it looks good to merge

**Comment by anselmolsm** [comment]
As a temporary way of testing (see original PR text), it looks OK.

**Comment by lbegani** [comment]
@anselmolsm I will merge this for now. To use Travis CI's build matrix feature, I will open an issue till its done.

**Pull request merged**
